# fly.toml file generated for lei-reactivities on 2023-03-26T19:45:56+08:00

app = "lei-reactivities"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "hkg"

[build]
  image = "leijacinto17/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dfumh6pll"
  Cloudinary__ApiKey="117311434635955"
  Facebook__AppId="1656669308087452"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
